### ISSUE TITLE
Feature request: Retry HTTPRequest::get() if fails

### ISSUE THREAD

**Issue by tsarquis88** [wazuh/wazuh-http-request#24]
### Description
It has been discovered that in some environments (Ubuntu container and Ubuntu AWS), the tool fails when performing many GET requests in a row and that if the ones that fail are re-tried, they succeed.

Because of that, this issue feature request aims to add the capability of retrying the GET if it fails.

## Expected
Retry n times if the value is explicitly passed as an argument.

Default value is 0 (no retry)

### DoD
- [x] Add feature
- [x] Add tests

**Comment by Damian-Mangold** [comment]
Issue closed as this change does not solve the ArchLinux migration problem. See [Investigate ArchAugmentator fetching alternatives](https://github.com/wazuh/intelligence-platform/issues/853)
