### ISSUE TITLE
Unchecked return value

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-http-request#48]
The `execute` method calls `curl_easy_setopt` with no error checking:

https://github.com/wazuh/wazuh-http-request/blob/3aa7c4b4a442f6ddfb52484fe766da769a8af50a/src/curlWrapper.hpp#L204

**Comment by Damian-Mangold** [comment]
Error code checking was added in a previous implementation

https://github.com/wazuh/wazuh-http-request/blob/main/src/curlWrapper.hpp#L188-L193


 so we can close this issue.
