### ISSUE TITLE
Implement non-blocking calls

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-http-request#49]
## Description

During the tests of https://github.com/wazuh/wazuh/pull/20967, it was found that the manager can't be gracefully stopped if there is a download in progress. 

See for example `src/shared_modules/content_manager/src/components/CtiDownloader.hpp`, there isn't a way to stop this line 

```c++
                m_urlRequest.get(HttpURL(URL + queryParameters), onSuccess, onError, outputFilepath);
```

It would be desirable that the `http-request` library allows non-blocking calls. For example, using `curl_multi_perform` instead of `curl_easy_perform`.

## DoD

- [ ] Analyze different options and propose the best method to allow non-blocking calls
- [ ] Make sure that the any user of the library can stop all the operations at any time, even when there is a download in progress
- [ ] Add UT
- [ ] CI Pass

**Comment by kevin-mcm** [comment]
# Update

- Trying to replicate in a local environment.
- Analyzing and investigating the suggestion to use `curl_multi_perform` instead of `curl_easy_perform`

**Comment by kevin-mcm** [comment]
# Update
- Doing some tests in local environment with `curl_multi_perform`

**Comment by kevin-mcm** [comment]
# Update
- The changes to replace `curl_easy_perform` with `curl_multi_perform` have been completed.
> [!IMPORTANT]
> - During the execution of unit and component tests, several issues were identified in return types and exception handling.
These issues may also exist in projects using this library.  Due to this, an analysis has been initiated for a new solution exploring a custom implementation to enable the use of `curl_multi_perform` without replacing `curl_easy_perform`.

**Comment by kevin-mcm** [comment]
# Update
- An interface was added to represent the curl handler. This interface is implemented by two new handlers:
  - Single Handler: It uses `curl_easy_perform`.
  - Multi Handler: It uses `curl_multi_perform`.
> [!NOTE]
> By default, the single handler is used, but the option to choose the multi handler is available in the `curlWrapper`
- Adding documentation and new tests for the Multi Handler.

**Comment by kevin-mcm** [comment]
# Update

- Create PR
- Add unit tests and component tests
- Apply suggestions from the code review

**Comment by kevin-mcm** [comment]
# Update

- Move `shouldRun` variable and `CurlHandlerTypeEnum` variable to the `IURLRequest` interface and implement behavior in the `UNIXSocketRequest` class and `HTTPRequest` class.
- Update unit tests and component tests.

**Comment by kevin-mcm** [comment]
# Update

- Improve unit tests
- Improve documentation
- Add unit tests for the cache class
