### ISSUE TITLE
Improve parameters interface

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-http-request#60]
## Description
There is no simple mechanism to add new parameters to the library methods. This means that the methods of the library are bloated with parameters:
https://github.com/wazuh/wazuh-http-request/blob/4d4b303d9aef19e032f27eeff7cc2be670fd0a3f/src/UNIXSocketRequest.cpp#L21-L28

## Proposal
Pass the parameters in a structure and generalize their implementation

## DoD
- [x] Proposal made
- [x] Proposal implemented

**Comment by sebasfalcone** [comment]
@Dwordcito Which release should we use for this issue?

**Comment by pereyra-m** [comment]
## Update

I begin with the issue. I'll propose a data structure that can hold all the parameters to improve the interface

**Comment by pereyra-m** [comment]
## Update

Issue on hold due to higher priority task:
- https://github.com/wazuh/wazuh/issues/24110

**Comment by pereyra-m** [comment]
## Update

I return to the task.
I keep updating the methods with the proposed structures.

**Comment by pereyra-m** [comment]
## Update

I continue updating the interface of all tests.

**Comment by pereyra-m** [comment]
## Update

Apply PR review changes.
