### ISSUE TITLE
Add timeout to requests

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-http-request#61]
## Description
Currently, there is no interface to configure the timeout for requests done using the library

This was evident while migrating SUSE, when the fetching mechanism stalled for 5 days

## Expected
Timeouts occur after a set period

### Blockers
We need first to improve the parameter addition mechanism:
- https://github.com/wazuh/wazuh-http-request/issues/60

## DoD
- [x] Feature added
- [x] Tests updated
- [ ] Ping @wazuh/devel-cppserver-div2 to update intelligence-platform

**Comment by sebasfalcone** [comment]
@Dwordcito Which release should we use for this issue?

**Comment by pereyra-m** [comment]
## Update

I begin with the implementation starting from the #60 branch

**Comment by pereyra-m** [comment]
## Update

I research a pre-existent issue with the multi-handler.

**Comment by pereyra-m** [comment]
## Update

I skip the failing tests and perform more testing.

**Comment by pereyra-m** [comment]
## Update

I fix the RTR warnings.

**Comment by pereyra-m** [comment]
## Update

I apply review changes.

**Comment by pereyra-m** [comment]
## Update

I commit review changes.

**Comment by pereyra-m** [comment]
## Update

Rebase branch.
